### ISSUE TITLE
Утечка памяти в клиенте

### ISSUE THREAD

**Issue by Nickstay** [ThePrimeTeam/YeOldeTinder#1]
У вас есть объекты с кешем, но я не заметил какие-либо действия по очищению кеша. Все данные по хорошему должны храниться в базе данных, и записываться в кэш при необходимости отправки пачкой, или при постоянном обращении к ним.

**Comment by Ilshat1415** [comment]
Добавлена очистка кеша. [https://github.com/ThePrimeTeam/YeOldeTinder/commit/129c61b30574d9f91b0b8dde8c58c07b0a518e32](url)
